# themesDir = "../.."
publishDir = "../"
theme = "hugo-smorg"
baseURL = "https://ospg.github.io/"
languageCode = "en-us"
title = "OSPG"
copyright = "&copy; OSPG"


#metaDataFormat = "yaml"

summaryLength = 20.0
paginate = 5.0
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsCodefences = true
enableGitInfo = false
enableRobotsTXT = true
enableEmoji = false

[author]
name = "OSPG"
email = "thisemaildoesnotexist@www.example.com"

[params]
debug = false
#cssPath = "css/smorg.min.css"
only_feed_summaries = true
fullname = "Open Source Programming Group"
description = "OSPG website"
logotype = "<span class=\"has-text-weight-bold\">OSPG</span>"
footer = " "
subfooter = "<i class=\"fab fa-github\"></i> <a href=\"https://github.com/OSPG\">github.com/OSPG</a>"

  [params.publisher]
  type = "Organization"
  name = "OSPG"
  logo = "https://avatars3.githubusercontent.com/u/23155720?s=200&v=4"

[menu]

  [[menu.sectionmenu]]
  name = "About"
  url = "about/"
  identifier = "about"
  weight = 10.0

  [[menu.sectionmenu]]
  name = "Contact Us"
  url = "about/contact/"
  parent = "about"
  weight = 101.0

  [[menu.sectionmenu]]
  name = "Projects"
  url = "project/"
  identifier = "project"
  weight = 20.0

  [[menu.sectionmenu]]
  name = "Godedupe"
  url = "project/godedupe/"
  parent = "project"
  weight = 201.0

  [[menu.sectionmenu]]
  name = "SV2"
  url = "project/sv2/"
  parent = "project"
  weight = 202.0

#  [[menu.sectionmenu]]
#  name = "Blog"
#  url = "post/"
#  weight = 30.0

[mediaTypes]

  [mediaTypes."application/atom"]
  suffixex = ["xml"]

[outputFormats]

  [outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "atom"

  [outputFormats.RSS]
  mediaType = "application/rss"
  baseName = "rss"

[outputs]
home = [
  "HTML",
  "Atom",
  "RSS"
]
