# themesDir = "../.."
publishDir = "../"
theme = "hugo-smorg"
baseURL = "http://ospg.github.io/"
languageCode = "en-us"
title = "OSPG"
copyright = "&copy; OSPG"


#metaDataFormat = "yaml"

summaryLength = 20.0
paginate = 5.0
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsCodefences = true
enableGitInfo = false
enableRobotsTXT = true
enableEmoji = false

[author]
name = "OSPG"
email = "thisemaildoesnotexist@www.example.com"

[params]
debug = false
#cssPath = "css/smorg.min.css"
only_feed_summaries = true
fullname = "Open Source Programming Group"
description = "160 characters or less describing you or your organization or your  site's purpose."
logotype = "<span class=\"has-text-weight-bold\">OSPG</span>"
footer = "An open source theme by <a href=\"https://mikewatkins.ca/\">Mike Watkins</a>"
subfooter = "<i class=\"fab fa-github\"></i> <a href=\"https://github.com/solutionroute/hugo-smorg\">github.com/solutionroute/hugo-smorg</a>"

  [params.publisher]
  type = "Organization"
  name = "OSPG"
  logo = "url to logo image"

[menu]

  [[menu.sectionmenu]]
  name = "About"
  url = "about/"
  identifier = "about"
  weight = 10.0

  [[menu.sectionmenu]]
  name = "Contact Us"
  url = "about/contact/"
  parent = "about"
  weight = 101.0

  [[menu.sectionmenu]]
  name = "Projects"
  url = "project/"
  identifier = "project"
  weight = 20.0

  [[menu.sectionmenu]]
  name = "Hugo-Smorg"
  url = "project/hugo-smorg/"
  parent = "project"
  weight = 201.0

  [[menu.sectionmenu]]
  name = "Blorg Bread Machine"
  url = "project/blorg-bread-machine/"
  parent = "project"
  weight = 202.0

  [[menu.sectionmenu]]
  name = "XYZ-1000"
  url = "project/xyz-1000/"
  parent = "project"
  weight = 203.0

  [[menu.sectionmenu]]
  name = "Blog"
  url = "post/"
  weight = 30.0

[mediaTypes]

  [mediaTypes."application/atom"]
  suffix = "xml"

[outputFormats]

  [outputFormats.Atom]
  mediaType = "application/atom"
  baseName = "atom"

  [outputFormats.RSS]
  mediaType = "application/rss"
  baseName = "rss"

[outputs]
home = [
  "HTML",
  "Atom",
  "RSS"
]
